name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy_to_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to test environment
        run: |
          # Example: Deploy Docker images to a test environment
          docker run -d -p 8080:80 your-username/image1
          docker run -d -p 8081:80 your-username/image2
          docker run -d -p 8082:80 your-username/image3
          docker run -d -p 8083:80 your-username/image4
          docker run -d -p 8084:80 your-username/image5
