name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check system status
        run: |
          systemctl status apache2
          systemctl status mysql

      - name: Generate Dockerfile
        run: |
          echo "FROM ubuntu:latest" > Dockerfile
          echo "RUN apt-get update && apt-get install -y apache2 php mysql-client" >> Dockerfile

  # Add more jobs or steps as needed 
