name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bash script
        run: ./script.sh
