name: Hello World workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hello:
    run-on: ubuntu-latest
    steps:
      - user: actions/checkout@v2
      - name: hello world
        run: echo "Hello World, This is the first job of my github Actions"
        shell: bash

  goodbye:
    run-on: ubuntu-latest
    steps:
      - name: good bye world
        run: echo "Good Bye World, My Second Job of GitHub Action"
