name: Create a comment on a new issues 

on:
    issues:
        types: [opened]

jobs:
  comment-with-action:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
	
comment-with-api:
	runs-on: ubuntu-latest
	steps:
      - name: Create comment with API
        run: |
		  gh api -X POST \
            https://api.github.com/repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
			-f body='
			Comment but from API call not action
			'
		env:
		  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
		  ORGANIZATION: ${{ github.event.organisation.login }}
          REPOSITORY: ${{ github.event.repository.number }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
